name: pose_detection_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Add plugin to any project simply added its as separate module and set the path like this
  #or put it anywhere you prefer and set the path relatively
  pose_detection_plugin:
    path: ../pose_detection_plugin

  camera: ^0.7.0+2
  
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/image/ic_swap_camera.png